### ISSUE TITLE
When creating new heartbeat event, error returned: cannot read property 'index' of undefined

### ISSUE THREAD

**Issue by bersilius** [arjunmehta/node-heartbeats#3]
I am using 3.1.1 version.
I created a new heart successfully. But when I try to create a new named event, I get this error:

TypeError: Cannot read property 'index' (beatevent.index) of undefined
    at Heart.killEvent (/node_modules/heartbeats/lib/heart.js:124:28)

In heart.js there is a function named: Heart.prototype.killEvent.
It is called in heart.js on line 104 when creating a named event. (if I am right it is for avoiding duplicate named events)
The function has two arguments: 'name' and 'beatevent'. But when its called it lacks the 'beatevent' argument. So 'beatevent.index' is undefined.
And the command -- this.events[beatevent.index] = undefined; -- on line 124 returns the error above.

Anyway thanks for this module, it makes timing and synchronizing really simple!

**Comment by arjunmehta** [comment]
@bersilius Thanks again for pointing it out.
Added this as something in the tests so it doesn't happen in the future.

Published the bug fix already [to npm](https://www.npmjs.com/package/heartbeats) and [released](https://github.com/arjunmehta/node-heartbeats/releases/tag/3.1.2).

Update your project! :D

**Comment by bersilius** [comment]
Updated. Issue solved!
Thanks again!
